In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread("lena.jpg", 1)


In [3]:
print(img)

[[[128 138 225]
  [127 137 224]
  [126 136 224]
  ...
  [126 145 236]
  [110 129 220]
  [ 86 104 197]]

 [[127 137 224]
  [127 137 224]
  [127 137 224]
  ...
  [130 150 235]
  [112 132 217]
  [ 83 102 189]]

 [[127 137 224]
  [127 137 224]
  [128 138 225]
  ...
  [127 148 230]
  [112 133 215]
  [ 85 105 190]]

 ...

 [[ 55  21  82]
  [ 54  20  81]
  [ 62  28  92]
  ...
  [ 82  71 175]
  [ 78  68 175]
  [ 74  65 175]]

 [[ 55  18  80]
  [ 56  19  81]
  [ 66  32  96]
  ...
  [ 82  69 177]
  [ 80  71 181]
  [ 81  72 183]]

 [[ 56  19  81]
  [ 58  21  83]
  [ 68  34  98]
  ...
  [ 81  68 176]
  [ 81  72 183]
  [ 84  74 188]]]


In [4]:
img = cv2.line(img, (0,0), (255,255), (168, 158, 50), 10) #50, 158, 168 (img,point1(pt1,pt2),clr,thickness)

In [5]:
img = cv2.arrowedLine(img, (0,255), (255,255), (153, 50, 168), 10) #50, 158, 168

In [6]:
cv2.imshow('image',img)

In [7]:
cv2.waitKey(0)

-1

In [8]:
cv2.destroyAllWindows()